### ISSUE TITLE
Half stars are not displayed correctly

### ISSUE THREAD

**Issue by paolorovella** [ProntoPro/awesome-react-rating#54]
### Is this a bug report?
Yes

### Environment
1. Operating system: macOS Mojave
2. Browser and version (if relevant): Chrome 70.0.3538.77

### Expected Behavior
![screenshot 2018-11-09 at 16 21 47](https://user-images.githubusercontent.com/9445954/48270984-95aac400-e43b-11e8-955a-e56e5c9c9fd0.png)

### Actual Behavior
![screenshot 2018-11-09 at 16 22 23](https://user-images.githubusercontent.com/9445954/48271018-a8bd9400-e43b-11e8-9bc3-42a25278602b.png)

**Comment by fes300** [comment]
this issue is orrible

**Comment by fes300** [comment]
@paolorovella should be ashamed of this
